### ISSUE TITLE
Multiversion docs are missing

### ISSUE THREAD

**Issue by RobPasMue** [ansys/pymapdl-reader#276]
The legacy reader was never adapted. We should do this.

Pinging @ansys/pyansys-core - if anybody can take the lead here, great. Otherwise I'll try to find some time (down the road)

**Comment by germa89** [comment]
honestly, shall we take the time for that? This library is supposed to in "deprecating" mode. Hence no features are going to be implemented, just fix.

**Comment by RobPasMue** [comment]
The note on the README currently states:

```md

This module may be depreciated in the future.

You are encouraged to use the new Data Processing Framework (DPF) modules at 
[PyDPF-Core](https://github.com/pyansys/pydpf-core) and [PyDPF-Post](https://github.com/pyansys/pydpf-post)
as they provide a modern interface to Ansys result files using a client/server interface using 
the same software used within Ansys Mechanical, but via a Python client.
```

Reality is that people are still using and we continue to do releases. Adapting it to multi-versions would only apply for the last version. I think it might be worth it. It's not that time consuming really. The theme is already up to date, and so are the actions.

**Comment by MaxJPRey** [comment]
If it is quite straight forward -which it should be-, I would add this feature, because this tool might stay for a while.
